name: Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            sudo apt-get update -qq
            pip install sphinx-rtd-theme
            pip install myst-parser
      - name: Build documentation
        run: |
            make html
      - name: Create commit
        run: |
            git clone https://github.com/ipa-cmh/manipulation_training.git --branch gh-pages --single-branch gh-pages
            mkdir -p gh-pages/
            rm -rf gh-pages/*
            touch gh-pages/.nojekyll
            cp -r ./_build/html/* gh-pages/
            mkdir -p gh-pages/robot_description/slides/
            cp -r ./robot_description/slides/* gh-pages/robot_description/slides/
            mkdir -p gh-pages/moveit/slides/
            cp -r ./moveit/slides/* gh-pages/moveit/slides/
            mkdir -p gh-pages/advanced_applicaiton_examples/slides/
            cp -r ./advanced_applicaiton_examples/slides/* gh-pages/advanced_applicaiton_examples/slides/
            cd gh-pages
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}